apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:    
  minio-root-user: cm9vdC11c2Vy 
  minio-root-password: cm9vdC1wYXNzd29yZA==