apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-init-scripts"
  namespace: {{ .Values.global.namespace }}
data:
  {{ (.Files.Glob "files/init-scripts/*.sql").AsConfig | indent 2 }}
