apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-init-sql"
  namespace: {{ .Values.global.namespace }}
data:
{{- $files := .Files.Glob "scripts/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ printf "%s" $file | indent 4 }}
{{- end }}