apiVersion: v2
name: fitness-app
description: A Helm chart for fitness-app
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "1.0.0"
    repository: "file://./charts/mongodb"
    enabled: true
  - name: vault
    version: "1.0.0"
    repository: "file://./charts/vault"
    enabled: true
  - name: minio
    version: "1.0.0"
    repository: "file://./charts/minio"
    enabled: true
  - name: redis
    version: "1.0.0"
    repository: "file://./charts/redis"
    enabled: true
  - name: nats
    version: "1.0.0"
    repository: "file://./charts/nats"
    enabled: true
  - name: settings-api
    version: "1.0.0"
    repository: "file://./charts/settings-api"
    enabled: true
  - name: identity-api
    version: "1.0.0"
    repository: "file://./charts/identity-api"
    enabled: true
  - name: gateway-api
    version: "1.0.0"
    repository: "file://./charts/gateway-api"
    enabled: true
