apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-init-scripts"
  namespace: {{ .Values.global.namespace }}
data:
{{- $files := .Files.Glob "mongo-init/*.js" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | indent 4 }}
{{- end }}
