apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configmapName }}
  namespace: {{ .Values.global.namespace }}
data:
  GatewayApi_Settings_Api_Url: http://settings-api-service:8000
  GatewayApi_ApiAuthenticationSettings_Address: http://identity-api-service:5000
  GatewayApi_OpenIdConnect_Authority: http://identity-api
  GatewayApi_ClientAuthenticationSettings_Issuer: http://identity-api-service:5000
  
  OpenIdConnect_Issuer: http://identity-api-service:5000
  OpenIdConnect_Authority: http://identity-api
  
  VaultClient_Address: http://vault-service:8200
  
  ServiceBus_Url: nats://nats-service:4222
  
  Database_Url: http://mongodb-service:27017