apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-deployment"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      enableServiceLinks: false
      containers:
      - name: "{{ .Chart.Name }}-container"
        image: {{ .Values.deployment.repository }}
        env:
          - name: EVENTSTORE_CLUSTER_SIZE
            value: "1"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: "All"
          - name: EVENTSTORE_START_STANDARD_PROJECTIONS
            value: "true"
          - name: EVENTSTORE_HTTP_PORT
            value: "2113"
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
            value: "true"