replicaCount: 1
secretName: fitness-app-minio-secret
minioRootUserKey: minio-root-user
minioRootPasswordKey: minio-root-password

image:
  repository: minio/minio

service:
  portConsole: 9091
  portS3: 9090