apiVersion: v1
kind: Secret
metadata:
  name: tariff-plan-secret
  namespace: tariff-plan-app
type: Opaque
data:
  PostgresUser: cG9zdGdyZXM=
  PostgresPassword: cG9zdGdyZXNwYXNzd29yZA==
  PostgresConnectionString: VXNlciBJRD1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlc3Bhc3N3b3JkO0hvc3Q9cG9zdGdyZXMtc2VydmljZS50YXJpZmYtcGxhbi1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPXBvc3RncmVzOw==
  PgAdminUser: YWRtaW5AYWRtaW4uY29t
  PgAdminPassword: YWRtaW4=
  MongoConnectionString: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNw==
  EventStoreDbConnectionString: ZXNkYjovL2V2ZW50c3RvcmUtc2VydmljZToyMTEzP3Rscz1mYWxzZQ==
