apiVersion: v2
name: fitness-app-infra
description: A Helm chart for tariff-plan-infra
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: eventstore
    version: "1.0.0"
    repository: "file://./charts/eventstore"
    enabled: true
  - name: mongodb
    version: "1.0.0"
    repository: "file://./charts/mongodb"
    enabled: true
  - name: nats
    version: "1.0.0"
    repository: "file://./charts/nats"
    enabled: true
  - name: postgres
    version: "1.0.0"
    repository: "file://./charts/postgres"
    enabled: true
