apiVersion: v1
kind: Secret
metadata:
  name: fitness-app-secret
  namespace: fitness-app
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
    
  minio-root-user: cm9vdC11c2Vy 
  minio-root-password: cm9vdC1wYXNzd29yZA==
    
  vault-dev-root-token-id: ZGV2LW9ubHktdG9rZW4=